pub mod diagnostics;
pub mod languages;
pub mod model;
pub mod speech;

pub use model::{DiagnosticSeverity, ReadRequest, ReaderDiagnostic, ReaderInput, ReaderOutput};

use speech::make_simple_speech_text;

/// Main entry point into the reusable code reader core.
///
/// This function receives editor-like input and returns speech-friendly output.
/// It does not know anything about VS Code, terminals, or speech engines.
pub fn read_code(input: ReaderInput) -> ReaderOutput {
    match input.request {
        ReadRequest::CurrentLine => read_current_line(&input),
        ReadRequest::CurrentScope => read_current_scope(&input),
        ReadRequest::FunctionParameters => read_function_parameters(&input),
        ReadRequest::FunctionSummary => read_function_summary(&input),
        ReadRequest::CurrentContext => read_current_context(&input),
        ReadRequest::DiagnosticsNearCursor => read_diagnostics_near_cursor(&input),
    }
}

/// Reads the current line from the source text.
fn read_current_line(input: &ReaderInput) -> ReaderOutput {
    let line_text = get_line(&input.source, input.cursor_line)
        .unwrap_or("")
        .trim();

    if line_text.is_empty() {
        return ReaderOutput {
            speech: "Blank line.".to_string(),
        };
    }

    // For now, Python is hard coded, but in the future, the plan is that
    // this will be more dynamic. Some other languages modules will need
    // to be made before this can be tested and implemented.
    if input.language.eq_ignore_ascii_case("python") {
        if let Some(speech) =
            languages::python::describe_current_line(&input.source, input.cursor_line)
        {
            return ReaderOutput { speech };
        }
    }

    let spoken_line = make_simple_speech_text(line_text);

    ReaderOutput {
        speech: format!("Current line: {spoken_line}"),
    }
}

/// Summarises the function containing the cursor.
///
/// For now, this only works for Python, but will be expanded in the future.
fn read_function_summary(input: &ReaderInput) -> ReaderOutput {
    if input.language.eq_ignore_ascii_case("python") {
        if let Some(speech) =
            languages::python::describe_function_summary(&input.source, input.cursor_line)
        {
            return ReaderOutput { speech };
        }

        return ReaderOutput {
            speech: "No Python function was found at the cursor.".to_string(),
        };
    }

    ReaderOutput {
        speech: format!(
            "Function summaries are not supported for {} yet.",
            input.language
        ),
    }
}

/// Reads only the parameters of the function containing the cursor.
///
/// For now, this only works for Python, but will be expanded in the future.
fn read_function_parameters(input: &ReaderInput) -> ReaderOutput {
    if input.language.eq_ignore_ascii_case("python") {
        if let Some(speech) =
            languages::python::describe_function_parameter_list(&input.source, input.cursor_line)
        {
            return ReaderOutput { speech };
        }

        return ReaderOutput {
            speech: "No Python function was found at the cursor.".to_string(),
        };
    }

    ReaderOutput {
        speech: format!(
            "Function parameters are not supported for {} yet.",
            input.language
        ),
    }
}

/// Describes the current code context at the cursor.
///
/// For now, this only works for Python, but will be expanded in the future.
fn read_current_context(input: &ReaderInput) -> ReaderOutput {
    if input.language.eq_ignore_ascii_case("python") {
        if let Some(speech) =
            languages::python::describe_current_context(&input.source, input.cursor_line)
        {
            return ReaderOutput { speech };
        }

        return ReaderOutput {
            speech: ("No Python context found at cursor.".to_string()),
        };
    }

    ReaderOutput {
        speech: format!(
            "Current context is not available for {} yet.",
            input.language
        ),
    }
}

/// Describes the current code scope at the cursor.
///
/// For now, this only works for Python, but will be expanded in the future.
fn read_current_scope(input: &ReaderInput) -> ReaderOutput {
    if input.language.eq_ignore_ascii_case("python") {
        if let Some(speech) =
            languages::python::describe_current_scope(&input.source, input.cursor_line)
        {
            return ReaderOutput { speech };
        }

        return ReaderOutput {
            speech: ("No Python scope found at cursor.".to_string()),
        };
    }

    ReaderOutput {
        speech: format!("Current scope is not available for {} yet.", input.language),
    }
}

/// Reads diagnostics on or near the cursor.
///
/// This is language-agnostic. Diagnostics are expected to be supplied by the
/// caller rather than generated by Tree-sitter.
fn read_diagnostics_near_cursor(input: &ReaderInput) -> ReaderOutput {
    let speech =
        diagnostics::describe_diagnostics_near_cursor(&input.diagnostics, input.cursor_line);

    ReaderOutput { speech }
}

/// Gets one line from a source string using a zero-based line number.
fn get_line(source: &str, cursor_line: usize) -> Option<&str> {
    source.lines().nth(cursor_line)
}

#[cfg(test)]
mod tests {

    use super::*;

    // Helper Functions
    fn reader_input(
        language: &str,
        source: &str,
        cursor_line: usize,
        request: ReadRequest,
    ) -> ReaderInput {
        ReaderInput {
            language: language.to_string(),
            source: source.to_string(),
            cursor_line,
            request,
            diagnostics: Vec::new(),
        }
    }

    fn reader_input_with_diagnostics(
        language: &str,
        source: &str,
        cursor_line: usize,
        request: ReadRequest,
        diagnostics: Vec<ReaderDiagnostic>,
    ) -> ReaderInput {
        ReaderInput {
            language: language.to_string(),
            source: source.to_string(),
            cursor_line,
            request,
            diagnostics,
        }
    }

    // Example Supported Language; Python is the hard-coded language
    fn supported_input(source: &str, cursor_line: usize, request: ReadRequest) -> ReaderInput {
        reader_input("python", source, cursor_line, request)
    }

    // Example Unsupported Language; Rust is the hard-coded language
    fn unsupported_input(source: &str, cursor_line: usize, request: ReadRequest) -> ReaderInput {
        reader_input("rust", source, cursor_line, request)
    }

    // Will enable when needed
    //fn diagnostic(
    //    severity: DiagnosticSeverity,
    //    message: &str,
    //    start_line: usize,
    //) -> ReaderDiagnostic {
    //    diagnostic_with_details(severity, message, start_line, None, None, None)
    //}

    fn diagnostic_with_details(
        severity: DiagnosticSeverity,
        message: &str,
        start_line: usize,
        end_line: Option<usize>,
        source: Option<&str>,
        code: Option<&str>,
    ) -> ReaderDiagnostic {
        ReaderDiagnostic {
            severity,
            message: message.to_string(),
            start_line,
            end_line,
            source: source.map(|value| value.to_string()),
            code: code.map(|value| value.to_string()),
        }
    }

    // Description Tests

    // Diagnostic Tests

    #[test]
    fn describes_no_diagnostics_near_cursor() {
        let input = supported_input(
            "print('hello')",
            0,
            ReadRequest::DiagnosticsNearCursor
        );

        let output = read_code(input);

        assert_eq!(output.speech, "No diagnostics near cursor.");
    }

    #[test]
    fn describes_error_diagnostic_on_cursor_line() {
        let input = reader_input_with_diagnostics(
            "python",
            "print(taxrate)",
            0,
            ReadRequest::DiagnosticsNearCursor,
            vec![diagnostic_with_details(
                DiagnosticSeverity::Error,
                "Undefined name taxrate",
                0,
                None,
                Some("pyright"),
                Some("reportUndefinedVariable"),
            )],
        );

        let output = read_code(input);

        assert_eq!(
            output.speech,
            "Error on current line: Undefined name taxrate."
        );
    }

    #[test]
    fn describes_nearest_diagnostic_when_cursor_line_has_no_diagnostic() {
        let input = reader_input_with_diagnostics(
            "python",
            "import math\n\nprint(taxrate)",
            1,
            ReadRequest::DiagnosticsNearCursor,
            vec![diagnostic_with_details(
                DiagnosticSeverity::Error,
                "Undefined name taxrate",
                2,
                None,
                Some("pyright"),
                Some("reportUndefinedVariable"),
            )],
        );

        let output = read_code(input);

        assert_eq!(
            output.speech,
            "Nearest diagnostic on line 3. Error: Undefined name taxrate."
        );
    }

    #[test]
    fn diagnostics_near_cursor_is_language_agnostic() {
        let input = reader_input_with_diagnostics(
            "rust",
            "fn main() {}",
            0,
            ReadRequest::DiagnosticsNearCursor,
            vec![diagnostic_with_details(
                DiagnosticSeverity::Warning,
                "Unused function main",
                0,
                None,
                Some("rust-analyzer"),
                Some("dead_code"),
            )],
        );

        let output = read_code(input);

        assert_eq!(
            output.speech,
            "Warning on current line: Unused function main."
        );
    }

    // Scope Tests

    #[test]
    fn describes_current_scope_at_top_level() {
        let input = supported_input(
            "import math\n\nx = 10\n",
            0,
            ReadRequest::CurrentScope
        );

        let output = read_code(input);

        assert_eq!(output.speech, "Current scope: top level.");
    }

    #[test]
    fn describes_current_scope_inside_function() {
        let input = supported_input(
            "def calculate_total(price):\n    return price",
            1,
            ReadRequest::CurrentScope,
        );

        let output = read_code(input);

        assert_eq!(output.speech, "Current scope: function calculate total.");
    }

    #[test]
    fn describes_current_scope_inside_if_statement() {
        let input = supported_input(
            "\
                def calculate_total(price):
                    if price > 0:
                        return price
            ",
            2,
            ReadRequest::CurrentScope,
        );

        let output = read_code(input);

        assert_eq!(
            output.speech,
            "Current scope: if statement, inside function calculate total."
        );
    }

    #[test]
    fn describes_current_scope_inside_for_loop() {
        let input = supported_input(
            "\
                def process_items(items):
                    for item in items:
                        print(item)
            ",
            2,
            ReadRequest::CurrentScope,
        );

        let output = read_code(input);

        assert_eq!(
            output.speech,
            "Current scope: for loop, inside function process items."
        );
    }

    #[test]
    fn describes_current_scope_inside_method_for_loop() {
        let input = supported_input(
            "\
                class Cart:
                    def print_items(self, items):
                        for item in items:
                            print(item)
            ",
            3,
            ReadRequest::CurrentScope,
        );

        let output = read_code(input);

        assert_eq!(
            output.speech,
            "Current scope: for loop, inside class Cart, function print items."
        );
    }

    // Context Tests

    #[test]
    fn describes_current_context_at_top_level() {
        let input = supported_input(
            "import math\n\nx = 10\n",
            0,
            ReadRequest::CurrentContext
        );

        let output = read_code(input);

        assert_eq!(output.speech, "Top level.");
    }

    #[test]
    fn describes_current_context_inside_function() {
        let input = supported_input(
            "def calculate_total(price, tax_rate):\n    return price * tax_rate",
            1,
            ReadRequest::CurrentContext,
        );

        let output = read_code(input);

        assert_eq!(output.speech, "Inside function calculate total.");
    }

    #[test]
    fn describes_current_context_inside_class() {
        let input = supported_input(
            "\
                class Cart:
                    tax_rate = 0.19

                    def calculate_total(self):
                        return 0
            ",
            1,
            ReadRequest::CurrentContext,
        );

        let output = read_code(input);

        assert_eq!(output.speech, "Inside class Cart.");
    }

    #[test]
    fn describes_current_context_inside_method() {
        let input = supported_input(
            "\
                class Cart:
                    def calculate_total(self, price):
                        return price
            ",
            2,
            ReadRequest::CurrentContext,
        );

        let output = read_code(input);

        assert_eq!(
            output.speech,
            "Inside class Cart, function calculate total."
        );
    }

    // Reading Tests

    // Function Tests

    #[test]
    fn reads_current_python_function_line_structurally() {
        let input = supported_input(
            "def calculate_total(price, tax_rate):\n    return price * tax_rate",
            0,
            ReadRequest::CurrentLine,
        );

        let output = read_code(input);

        assert_eq!(
            output.speech,
            "Function calculate total. Parameters: price; tax rate."
        );
    }

    #[test]
    fn reads_current_typed_python_function_line_structurally() {
        let input = supported_input(
            "def calculate_total(price: float, tax_rate: float = 0.19) -> float:\n    return price * tax_rate",
            0,
            ReadRequest::CurrentLine,
        );

        let output = read_code(input);

        assert_eq!(
            output.speech,
            "Function calculate total. Parameters: price, float; tax rate, float, default zero point one nine. Returns float."
        );
    }

    // Parameter Tests

    #[test]
    fn reads_python_function_parameters_when_cursor_is_on_def_line() {
        let input = supported_input(
            "def calculate_total(price, tax_rate):\n    return price * tax_rate",
            0,
            ReadRequest::FunctionParameters,
        );

        let output = read_code(input);

        assert_eq!(output.speech, "Parameters: price; tax rate.");
    }

    #[test]
    fn reads_python_function_parameters_when_cursor_is_inside_body() {
        let input = supported_input(
            "def calculate_total(price, tax_rate):\n    return price * tax_rate",
            1,
            ReadRequest::FunctionParameters,
        );

        let output = read_code(input);

        assert_eq!(output.speech, "Parameters: price; tax rate.");
    }

    #[test]
    fn reads_typed_python_function_parameters_when_cursor_is_inside_body() {
        let input = supported_input(
            "def calculate_total(price: float, tax_rate: float = 0.19) -> float:\n    return price * tax_rate",
            1,
            ReadRequest::FunctionParameters,
        );

        let output = read_code(input);

        assert_eq!(
            output.speech,
            "Parameters: price, float; tax rate, float, default zero point one nine."
        );
    }

    #[test]
    fn reads_no_parameters_for_function_without_parameters() {
        let input = supported_input(
            "def main():\n    return 0",
            1,
            ReadRequest::FunctionParameters,
        );

        let output = read_code(input);

        assert_eq!(output.speech, "No parameters.");
    }

    // Line Tests

    #[test]
    fn reads_blank_line() {
        let input = supported_input(
            "def example():\n\n    return 1",
            1,
            ReadRequest::CurrentLine,
        );

        let output = read_code(input);

        assert_eq!(output.speech, "Blank line.");
    }

    #[test]
    fn handles_cursor_line_past_end_of_file() {
        let input = supported_input(
            "print('hello')",
            20,
            ReadRequest::CurrentLine,
        );

        let output = read_code(input);

        assert_eq!(output.speech, "Blank line.");
    }

    // Fallback Tests

    #[test]
    fn falls_back_to_simple_speech_for_python_return_line() {
        let input = supported_input(
            "def calculate_total(price, tax_rate):\n    return price * tax_rate",
            1,
            ReadRequest::CurrentLine,
        );

        let output = read_code(input);

        assert_eq!(output.speech, "Current line: return price * tax rate");
    }

    // Summarising Tests

    // Summarising Function Tests

    #[test]
    fn summarizes_python_function_when_cursor_is_on_def_line() {
        let input = supported_input(
            "def calculate_total(price, tax_rate):\n    return price * tax_rate",
            0,
            ReadRequest::FunctionSummary,
        );

        let output = read_code(input);

        assert_eq!(
            output.speech,
            "Function calculate total. Parameters: price; tax rate."
        );
    }

    #[test]
    fn summarizes_python_function_when_cursor_is_inside_body() {
        let input = supported_input(
            "def calculate_total(price, tax_rate):\n    return price * tax_rate",
            1,
            ReadRequest::FunctionSummary,
        );

        let output = read_code(input);

        assert_eq!(
            output.speech,
            "Function calculate total. Parameters: price; tax rate."
        );
    }

    #[test]
    fn summarizes_typed_python_function_when_cursor_is_inside_body() {
        let input = supported_input(
            "def calculate_total(price: float, tax_rate: float = 0.19) -> float:\n    return price * tax_rate",
            1,
            ReadRequest::FunctionSummary,
        );

        let output = read_code(input);

        assert_eq!(
            output.speech,
            "Function calculate total. Parameters: price, float; tax rate, float, default zero point one nine. Returns float."
        );
    }

    // Null or Empty Return Tests

    // Null or Empty Function Return Tests

    #[test]
    fn returns_message_when_no_python_function_found_at_cursor() {
        let input = supported_input(
            "import math\n\nx = 10\n",
            0,
            ReadRequest::FunctionSummary,
        );

        let output = read_code(input);

        assert_eq!(output.speech, "No Python function was found at the cursor.");
    }

    #[test]
    fn returns_message_when_function_summaries_not_supported_for_language() {
        let input = unsupported_input(
            "fn main() {}",
            0,
            ReadRequest::FunctionSummary,
        );

        let output = read_code(input);

        assert_eq!(
            output.speech,
            "Function summaries are not supported for rust yet."
        );
    }

    // Null or Empty Context Return Tests

    #[test]
    fn returns_message_when_current_scope_not_supported_for_language() {
        let input = unsupported_input(
            "fn main() {}",
            0,
            ReadRequest::CurrentScope,
        );

        let output = read_code(input);

        assert_eq!(
            output.speech,
            "Current scope is not available for rust yet."
        );
    }

    #[test]
    fn returns_message_when_current_context_not_supported_for_language() {
        let input = unsupported_input(
            "fn main() {}",
            0,
            ReadRequest::CurrentContext,
        );

        let output = read_code(input);

        assert_eq!(
            output.speech,
            "Current context is not available for rust yet."
        );
    }

    // Null or Empty Parameter Return Tests

    #[test]
    fn returns_message_when_no_python_function_found_for_parameters() {
        let input = supported_input(
            "import math\n\nx = 10\n",
            0,
            ReadRequest::FunctionParameters,
        );

        let output = read_code(input);

        assert_eq!(output.speech, "No Python function was found at the cursor.");
    }

    #[test]
    fn returns_message_when_function_parameters_not_supported_for_language() {
        let input = unsupported_input(
            "fn main() {}",
            0,
            ReadRequest::FunctionParameters,
        );

        let output = read_code(input);

        assert_eq!(
            output.speech,
            "Function parameters are not supported for rust yet."
        );
    }

    // Deserialisation Tests
    #[test]
    fn deserializes_json_input_for_diagnostics_near_cursor_without_diagnostics() {
        let json = r#"
        {
            "language": "python",
            "source": "print('hello')",
            "cursor_line": 0,
            "request": "diagnostics_near_cursor"
        }
        "#;

        let input: ReaderInput = serde_json::from_str(json).unwrap();

        assert_eq!(input.language, "python");
        assert_eq!(input.cursor_line, 0);
        assert_eq!(input.request, ReadRequest::DiagnosticsNearCursor);
        assert!(input.diagnostics.is_empty());
    }

    #[test]
    fn deserializes_json_input_for_diagnostics_near_cursor_with_diagnostics() {
        let json = r#"
        {
            "language": "python",
            "source": "print(taxrate)",
            "cursor_line": 0,
            "request": "diagnostics_near_cursor",
            "diagnostics": [
                {
                    "severity": "error",
                    "message": "Undefined name taxrate",
                    "start_line": 0,
                    "source": "pyright",
                    "code": "reportUndefinedVariable"
                }
            ]
        }
        "#;

        let input: ReaderInput = serde_json::from_str(json).unwrap();

        assert_eq!(input.language, "python");
        assert_eq!(input.cursor_line, 0);
        assert_eq!(input.request, ReadRequest::DiagnosticsNearCursor);
        assert_eq!(input.diagnostics.len(), 1);
        assert_eq!(input.diagnostics[0].severity, DiagnosticSeverity::Error);
        assert_eq!(input.diagnostics[0].message, "Undefined name taxrate");
        assert_eq!(input.diagnostics[0].start_line, 0);
        assert_eq!(input.diagnostics[0].source, Some("pyright".to_string()));
        assert_eq!(
            input.diagnostics[0].code,
            Some("reportUndefinedVariable".to_string())
        );
    }

    #[test]
    fn deserializes_json_input_for_current_scope() {
        let json = r#"
        {
            "language": "python",
            "source": "def calculate_total(price):\n    return price",
            "cursor_line": 1,
            "request": "current_scope"
        }
        "#;

        let input: ReaderInput = serde_json::from_str(json).unwrap();

        assert_eq!(input.language, "python");
        assert_eq!(input.cursor_line, 1);
        assert_eq!(input.request, ReadRequest::CurrentScope);
    }

    #[test]
    fn deserializes_json_input_for_current_context() {
        let json = r#"
        {
            "language": "python",
            "source": "def calculate_total(price, tax_rate):",
            "cursor_line": 0,
            "request": "current_context"
        }
        "#;

        let input: ReaderInput = serde_json::from_str(json).unwrap();

        assert_eq!(input.language, "python");
        assert_eq!(input.cursor_line, 0);
        assert_eq!(input.request, ReadRequest::CurrentContext);
    }

    #[test]
    fn deserializes_json_input_for_current_line() {
        let json = r#"
        {
            "language": "python",
            "source": "def calculate_total(price, tax_rate):",
            "cursor_line": 0,
            "request": "current_line"
        }
        "#;

        let input: ReaderInput = serde_json::from_str(json).unwrap();

        assert_eq!(input.language, "python");
        assert_eq!(input.cursor_line, 0);
        assert_eq!(input.request, ReadRequest::CurrentLine);
    }

    #[test]
    fn deserialize_json_input_for_function_summary() {
        let json = r#"
        {
            "language": "python",
            "source": "def calculate_total(price, tax_rate):",
            "cursor_line": 0,
            "request": "function_summary"
        }
        "#;

        let input: ReaderInput = serde_json::from_str(json).unwrap();

        assert_eq!(input.language, "python");
        assert_eq!(input.cursor_line, 0);
        assert_eq!(input.request, ReadRequest::FunctionSummary);
    }

    #[test]
    fn deserializes_json_input_for_function_parameters() {
        let json = r#"
        {
            "language": "python",
            "source": "def calculate_total(price, tax_rate):",
            "cursor_line": 0,
            "request": "function_parameters"
        }
        "#;

        let input: ReaderInput = serde_json::from_str(json).unwrap();

        assert_eq!(input.language, "python");
        assert_eq!(input.cursor_line, 0);
        assert_eq!(input.request, ReadRequest::FunctionParameters);
    }

    // Serialisation Tests

    #[test]
    fn serializes_json_output() {
        let output = ReaderOutput {
            speech: "Current line: def example".to_string(),
        };

        let json = serde_json::to_string(&output).unwrap();

        assert_eq!(json, r#"{"speech":"Current line: def example"}"#);
    }
}
